# Data Types and Management
---
## Learning Objectives:

- To have an understanding of objects and variable types in Python.


- To understand the difference between ints, floats, strings and tuples.


- To understand and be able to use lists, tuples, dictionaries and numpy arrays.


- To be able to define and use a function in Python. 


- Understand what a Python Module is.

## Overview

In this session we are going to develop our understanding of what Python is and how we use it by learning about the different objects used in Python. Take some time to read through these materials and try to understand what the snippets of code provided are doing. 

Note: Sometimes we want to write notes in our script that do not interfere with our code. These are called comments. We can add a comment into our code by typing “#” before the text we wish to comment. **Use comments sparingly - our code should be understandable without them!**

In [ ]:
# This is how I would write a comment in my code.

---
## Strings

A string (str) is simply a collection of words and or numbers. In Python we can write a string by placing some information in either ‘ ’ or “ “. For example, below I will create a string and get the computer to print it out for me using the print() command:

In [ ]:
myString = "This is an example of a string!"
print(myString)

# I can also print a string without saving it as a variable.
print("How many odd numbers are there between 0 and 10?")

# If I want to print a number, I can simply insert it into the 
# print command brackets separated from my string by a comma:
print("How many odd numbers are there between 0 and 10?", 5, "?")

Often it will be useful to take just a section of a string or perhaps a specific character. The way to do this is by slicing, which is the term used to describe splitting data into smaller chunks. We can slice lots of things (lists and arrays), but here let's demonstrate how we can slice a string.

In [ ]:
newString = "Go and explore the peak district!"

# Note that the Oth element of the string is the first letter of our string. 
# In Python all indexes start at zero NOT one!

print(newString[0])
print(newString[3])
print(newString[5])

In [ ]:
# We can also slice strings into sectionns. For example, the command below will print the first 5 
# characters of our string, but not the 5th:
print(newString[0:5])

In [ ]:
# Alternatively, we may wish to index from the end of our string. For example, if we wanted to print the from 
# the last five characters from the end to two before the end of the string we could slice as follows:
print(newString[-5:-2])

In [ ]:
#Perhaps we want to print characters of our string, but skip every other character:
print(newString[0:34:2])

In [ ]:
# We could always print the string backwards?
print(newString[::-2])

Above we have shown how we may slice strings into smaller chunks of information. In other instances it may be useful to merge strings together - this is known as concatenating. 

In [1]:
string1 = "Go and explore"
string2 = "the peak district!"

# We can concatenate the strings using "+". Note I need to add a space.
sentence = string1 + " " + string2
print(sentence)

Go and explore the peak district!


Using Python we are also able to do lots of things with strings. For example, we can replace specific words, change which letters are capitalised, search for terms in the string, or “multiply” the string.

In [2]:
# We can also use functions built into Python to modify our string. 
# For example, perhaps we live in the north-west and the peak district is a little far out for us:
newString = sentence.replace('peak', 'lake')
print(newString)

Go and explore the lake district!


In [ ]:
# Finally, perhaps you still haven't gone out and explored and I wish to be a little louder:
newString = newString.upper()
print(newString)

In [ ]:
# Now you have finally explored the lake district you decide to write a book about it. 
# The title of the book needs to be formatted nicely:
newString = newString.title()
print(newString)

In [ ]:
# Remind me, did we explore in the lake district or the peak district? Lets check our string to find out.
searchTerm1 = "lake"
searchTerm2 = "peak"
print("It is", searchTerm1 in sentence, 'that', searchTerm1, 'is in the sentence.')
print("It is", searchTerm2 in sentence, 'that', searchTerm2, 'is in the sentence.')

In [ ]:
# Are we enjoying learning about strings!?
politeAnswer = "yeah "
disingenuousAnswer = politeAnswer * 3
print(politeAnswer)
print(disingenuousAnswer)

---
## Ints and floats

Now that we have covered the basics of strings, let's consider how we deal with numbers in Python. Simply put we can either use ints or floats. An int is an integer number whereas a float is a floating point number (does not need to be a whole number).

In [1]:
myInteger = 1
myFloat = 15.0

# Let's see what class the interpreter assigns to each of our variables:
print(myInteger, type(myInteger))
print(myFloat,type(myFloat))

1 <class 'int'>
15.0 <class 'float'>


Something to note is that when we perform calculations using floats and ints, the output will also either be a float or an integer based on the calculation performed. If we only use ints the output will also be an int, but if we use a float at any point in our calculation, the output will be a float.

In [2]:
# Here we demonstrate how types may be converted during calculation
print(type(15*myInteger))
print(type(1*myFloat))
print(type(myInteger*myFloat))
print(type(myInteger+myFloat))

<class 'int'>
<class 'float'>
<class 'float'>
<class 'float'>


As we may need to use specifically either a float or an int later in our script, it is very convenient that we are able to convert variable types very easily in Python.

In [3]:
# By putting our float inside the int() function, we can convert it back into an int
newVariable = int(myInteger*myFloat)
print(newVariable,type(newVariable))

15 <class 'int'>


In [4]:
# If we so wish we can also convert our variable back into a float
newVariable = float(newVariable)
print(newVariable,type(newVariable))

15.0 <class 'float'>


In [5]:
# We can also convert our variable into a string, but note how this impact the calculations we perform:
newVariable =str(newVariable)
print(5*newVariable)

15.015.015.015.015.0


As a consequence of how computers store information using binary (1’s and 0’s), often the number we tell the computer to use is not the exact number it uses, although using a 64bit computer, the difference will be very small!

If we execute the following code calculation in our computer we would expect it to return the answer 0.55, but this is not the answer we get...

In [6]:
4.9 - 4.845

0.055000000000000604

---
## Lists and Tuples

Up to this point we have only considered how to store single items of information, but often we will need to store more information. For example, if we wanted to plot a graph we would need the information corresponding to the x-coordinates and the information corresponding to the y-coordinates. It would be impractical to store every single x and y value as a single variable.

In Python a list is just a collection of information. To define a list we simply put our information in a set of square brackets and separate each item using a comma. As before we can slice, concatenate and index our list items.


In [3]:
nordicCountries = ["Iceland", "Denmark", "Norway", "Sweden", "Finland"]
balticCountries = ["Estonia", "Lativa", "Lithuania"]

In [5]:
# Using the index I can extract items from a list or slice the list:
islandNations = nordicCountries[0]
print("The island nations that are part of the nordic nations include: ", islandNations)
continentalNordics = nordicCountries[1:5]
print("The continental nations that are part of the nordic nations include: ", continentalNordics)

The island nations that are part of the nordic nations include:  Iceland
The continental nations that are part of the nordic nations include:  ['Denmark', 'Norway', 'Sweden', 'Finland']


In [6]:
# Similarly, I can concatenate lists:
coolContinentalCountries = balticCountries + continentalNordics
print("Of the nations that form the baltic and nordic countries, the following are continental: \n", coolContinentalCountries)

Of the nations that form the baltic and nordic countries, the following are continental: 
 ['Estonia', 'Lativa', 'Lithuania', 'Denmark', 'Norway', 'Sweden', 'Finland']


In [7]:
# A list can be made up from any collection of information:
randomList = ["Aston Martin", 11, ["apple", "pear", "orange"], 3.14159]
print(randomList)
print("The third item in my list is", randomList[2])
print("The last two items in my list are", randomList[-2:])

['Aston Martin', 11, ['apple', 'pear', 'orange'], 3.14159]
The third item in my list is ['apple', 'pear', 'orange']
The last two items in my list are [['apple', 'pear', 'orange'], 3.14159]


A tuple is very similar to a list, the difference being that a tuple is immutable (it cannot be changed). We can create a tuple by putting our items between round brackets and separated by commas. Although we can still index, slice and concatenate tuples, there are only two methods associated with them: index and count.

In [8]:
myTuple = ("England", "Ireland", "Scotland", "Wales", "Wales", "France", "Netherlands")

# The count method will tell us how many instances of an item appear in the tuple
print(myTuple.count("Wales"))

#The index method will tell us where an item appears in the tuple
print(myTuple.index("Netherlands"))

2
6


---
## Dictionaries

A dictionary may be used to store information with specific associated keys. For example, perhaps we would like to catalogue information and would like to be able to reference these properties later in our script.

In [9]:
VW_Cars = {
    "Golf": {
        "year": 2022,
        "price": 25000,
        "engine": "1.4L TSI",
        "horsepower": 147,
        "fuel_type": "Petrol"
    },
    "Polo": {
        "year": 2021,
        "price": 20000,
        "engine": "1.0L MPI",
        "horsepower": 79,
        "fuel_type": "Petrol"
    },
    "Passat": {
        "year": 2022,
        "price": 35000,
        "engine": "2.0L TSI",
        "horsepower": 174,
        "fuel_type": "Petrol"
    },
}

Note how the dictionary above is structured. As we use dictionaries to store information, there are lots of methods we can use to find, extract, and remove items from the dictionary. Below is an example of how we may use the .keys() and .get() methods.

In [10]:
# We can find out what the keys in our dictionary are using the .keys() command:
print("The keys in our car catalogue are:", VW_Cars.keys())

The keys in our car catalogue are: dict_keys(['Golf', 'Polo', 'Passat'])


In [11]:
# We can extract information from the dictionary as follows using the .get() command:
model = "Golf"
print("Information for VW", model, ":", VW_Cars.get(model))

Information for VW Golf : {'year': 2022, 'price': 25000, 'engine': '1.4L TSI', 'horsepower': 147, 'fuel_type': 'Petrol'}


In [12]:
# Or simply:
print("Information for VW Passat:", VW_Cars["Passat"])

Information for VW Passat: {'year': 2022, 'price': 35000, 'engine': '2.0L TSI', 'horsepower': 174, 'fuel_type': 'Petrol'}


---
## Numpy Arrays

One of the most ubiquitous data structures is the array.  An array is a matrix of numbers that can be any number of dimensions. For now, we will only use 2D arrays to make visualising them easier. We will use a type of array called a Numpy Array, this is very common and used by nearly everyone. To use numpy we have to import the numpy library into Python to give us access to the array commands. To do this we simply write an import command at the top of our Python script.

In [2]:
import numpy as np
# The "as np" is present as it means that each time we call something from the numpy library, we only 
# need to write "np." before the numpy command, rather than "numpy." e.g. "np.mean" vs "numpy.mean"

It is vital that you understand how to make and use numpy arrays as you will be using throughout the semester for data analysis and plotting. Take time to read through the code below and try to understand what it is doing. 

In [2]:
# Lets start by making a simple 1D array:
array1 = np.array([1,2,3,4,5,6,7,8,9])
print(array1)

print('The first value in my array is', array1[0])
print('The last value in my array is', array1[-1])
print('The first 3 values in my array are', array1[0:3])

[1 2 3 4 5 6 7 8 9]
The first value in my array is 1
The last value in my array is 9
The first 3 values in my array are [1 2 3]


In [3]:
# It is often useful to store information in 2 dimensional arrays:
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# When extracting information/slicing 2D arrays, we must provide additinal information 
# (corresponding to the x index and the y index)

print('The value in the top left is', array2[0,0]) 
print('The first row is', array2[0,:]) # prints the whole row
print('The middle column is', array2[:,1]) # prints the whole column
print('The mean of the 1D array is', np.mean(array1))
print('The mean of the 2D array is', np.mean(array2))

The value in the top left is 1
The first row is [1 2 3]
The middle column is [2 5 8]
The mean of the 1D array is 5.0
The mean of the 2D array is 5.0


In [5]:
# We can also ask numpy to perform calculations using a specific axis, thus giving us three different mean values:
print('The mean of the 2D array in Y is', np.mean(array2, axis=0))
print('The mean of the 2D array in X is', np.mean(array2, axis=1))

The mean of the 2D array in Y is [4. 5. 6.]
The mean of the 2D array in X is [2. 5. 8.]


When using numpy arrays, we are not limited to performing calculations on a single array, we can perform calculations using multiple arrays e.g. addition, subtraction, multiplication and matrix calculations. Furthermore, within the numpy library there are many different methods that can be called, for example, we may wish to resize our array, or determine how many individual elements it is made up from.

In [6]:
# Let's resize our first array so that it has the same dimensions as our second:
print('Shape', np.shape(array1))
array1 = np.reshape(array1,[3,3]) # Lets make it 3x3
print('Shape', np.shape(array1))
print(array1)

Shape (9,)
Shape (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Summation
print(array1+array2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [8]:
# Multiplication
print(array1*array2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [9]:
#Real matrix multiplication
print(np.matmul(array1, array2))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


### Common Numpy Things

When working with data in the labs, it is likely that you will want to perform calculations on linear sets of data. For example, perhaps you would like to mutliply all of your measured data by a constant or calculate the average from a series of repeat measurements. This can easily be done using numpy arrays - when using them you can simply write an equation in terms of the array and python will know you want to create a new array where every value has been modified. 

For example, let's take a one dimensional numpy array and mutliply every value by 2 before adding 3:

In [3]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

newData = (2 * data) + 3
print(newData)

[ 5  7  9 11 13 15 17 19 21 23]


We could then use newData in subsequent calculations. We can aslo make use of useful numpy functions such as sum or average. For example:

In [4]:
mean = np.average(data)
print("The mean of the data is: ", mean)

total = np.sum(data)
print("The sum of the data is: ", total)

The mean of the data is:  5.5
The sum of the data is:  55


Just think, being able to do maths in this way would make performing calculations much more efficicent. For example I could very quickly calculate something like the standard deviation of a series of measurements by using a numpy array:

$$ 
\sigma_{N-1} = \sqrt{\frac{\sum{\left(x_i-\bar{x}\right)^2}}{N-1}}.
$$

In [5]:
data1 = np.array([5, 5.1, 4.9, 5.2, 5.2, 5.1])

# 1. Calculate the mean
mean1 = np.average(data1)

# 2. Calculate the square of the deviation from the mean for each value
x_minus_xbar_squared = (data1 - mean1)**2

# 3. Calculate the numerator and denominator of the standard deviation equation
numerator = np.sum(x_minus_xbar_squared)
denominator = len(data1) - 1 #len() simply tells us how many values are in the array.

#Calculate the standard deviation
standardDeviation = np.sqrt(numerator/denominator)

#print the result
print("The standard deviation for the data above is given as:", np.round(standardDeviation,2))

The standard deviation for the data above is given as: 0.12


The method above is valid, but as this is the sort of calculation that is fairly common there is a pre-defined numpy function that will do the same for us:

In [6]:
standardDeviation2 = np.std(data1, ddof = 1)
print("Numpy calculates the standard deviation to be:", np.round(standardDeviation2,2))

Numpy calculates the standard deviation to be: 0.12


Before we move onto the next topic, I would like to make you aware of a few tools in numpy that you may find useful:

- [np.zeros()](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) - used to create an array filled with zeros,

- [np.ones()](https://numpy.org/doc/stable/reference/generated/numpy.ones.html) - used to create an array filled with ones,

- [np.linspace()](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) - used to create a 1D array with linearly spaced values between a start and stop, where we define how many values we would like in our array,

- [np.arange()](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)- used to create a 1D array with values between a start and stop, where we define the step increment between the two values.

- [np.round()](https://numpy.org/doc/2.0/reference/generated/numpy.round.html) - used to round a value to a particular number of decimals (as in the examples above). 

Examples of the these numpy tools are provided below:

In [7]:
zerosArray = np.zeros([3,6])
print(zerosArray)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [8]:
onesArray = np.ones([3,6])
print(onesArray)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [9]:
l_Array = np.linspace(0, 9, 10)
print(l_Array)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [10]:
a_Array = np.arange(0, 10, .5)
print(a_Array)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


---
## Activities

```{admonition} Downloads
:class: note

The file linked [here](https://drive.google.com/drive/folders/1cVJNZNqWNpGSFj4yc2ZAs3Q5kqDQ7z3a?usp=sharing) contains all of the materials required for this weeks tasks. Please download copies of the file contents and organise them into your Google Drive to work on. 
```

### 1. Strings 

Save your first, middle (if applicable) and as three different variables (first, middle, last). Use the print statement and appropriate string methods to:

1. Print the statement “My full name is: first middle last”.
2. Print the statement in all caps.
3. Print the statement in capitalising only the first letter of each word.
4. Print the statement backwards.
5. Print every second letter of the statement.

Create a new variable “age” and set it equal to your age. Make a new string that says “and my age is x”. Concatenate the first and second statements into a new sentence.

---
### 2. Calculations

Using the [len() function](https://www.w3schools.com/python/ref_func_len.asp), determine how many letters are in your first and second names. Ensure that these numbers are stored as variables (first & second). The len() function determines the length of something, this may be a string or a list or an array etc. An example is shown below:

In [1]:
aLongName = "Daenerys Stormborn of House Targaryen, the First of Her Name, Queen of the Andals and the First Men, Protector of the Seven Kingdoms, the Mother of Dragons, the Khaleesi of the Great Grass Sea, the Unburnt, the Breaker of Chains"

print(len(aLongName))

# This would return and print the number of characters (letters and spaces) in aLongName - in this case 228.

228


From the two saved variables determine:

1. The product of “first” and “second”.
2. The radio of “first” to “second”.
3. The value of “first” to the power of “second”. 
4. The total number of letters in your first and second name.
5. The difference in the number of characters of your first and second name.

For each calculation above, get the computer to print out a statement such as “the product of first and second is … ”.

---
### 3. Lists and Numpy Arrays

Generate a list of 10 items and:

1. Print the 7th item of the list.
2. Print the first 4 items of the list.
3. Print the 2nd, 4th, 6th and 8th items of the list.

Generate a numpy array containing the numbers 0 to 12:

4. Determine all values of the times tables up to 12 using this array (e.g. 0x0 to 12x12). 
5. Print each array containing the times tables e.g. (0, 2, 4, 6… and then 0, 3, 6, 9…).